dist: xenial
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true

sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7

    packages:
      - libeigen3-dev
      - build-essential
      - libclang-7-dev
      - llvm-7-dev

script:
  - cargo test --release

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
