# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required
# addons:
#   apt:
#     packages:
#       - libssl-dev

before_install:
  - set -e
  - rustup self update

# install:
#   - cargo install cargo-travis || true

script:
  - cargo build --release
  - cargo test --release

# after_success:
#   - cargo doc --release
#   - cargo doc-upload || true

# after_success: |
#   if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
#     `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin`
#     # Uncomment the following line for coveralls.io
#     # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

#     # Uncomment the following two lines create and upload a report for codecov.io
#     cargo tarpaulin --out Xml
#     bash <(curl -s https://codecov.io/bash)

#     cargo doc
#     cargo doc-upload
#   fi

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
