[package]
name = "trajectories-jerk"
version = "0.1.0"
authors = ["James Waples <james@wapl.es>"]
edition = "2018"

[dependencies]
nalgebra = "0.18.1"
serde_derive = "1.0.101"
csv = "1.1.1"
serde = "1.0.101"

[dev-dependencies]
approx = "0.3.2"
