[package]
authors = ["James Waples <jamwaffles@gmail.com>"]
name = "trajectories"
version = "0.1.0"
[dependencies]
approx = "0.3.0"
image = "0.19.0"
imageproc = "0.15.0"
nalgebra = "0.16.0"
trajectories-sys = { path = "../trajectories-sys" }
csv = "1.0.1"
serde = "1.0.78"
serde_derive = "1.0.78"
