[package]
authors = ["James Waples <james@wapl.es>"]
name = "trajectories-sys"
version = "0.1.0"
[build-dependencies]
bindgen = "0.48.1"

[build-dependencies.cc]
features = ["parallel"]
version = "1.0.32"

[dependencies]
libc = "0.2.50"
