[package]
authors = ["James Waples <jamwaffles@gmail.com>"]
name = "trajectories-sys"
version = "0.1.0"
[build-dependencies]
bindgen = "0.44.0"

[build-dependencies.cc]
features = ["parallel"]
version = "1.0.26"

[dependencies]
libc = "0.2.45"
